import { ArrowUpRight, FlaskConical, Lightbulb } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PublicSiteFooter, PublicSiteHeader } from '../components/PublicSiteChrome';
import { FruitClassifier, PromptBuilder, EthicsPreview } from '../components/StudioExperiments';
import Reveal from '../components/Reveal';
export default function PlaygroundPage() {
  return <div className="signal-landing studio-interior"><PublicSiteHeader /><main id="main-content" tabIndex={-1}>
    <section className="studio-page-hero"><div className="landing-width"><p className="studio-eyebrow"><FlaskConical size={17} /> THE SIGNAL PLAYGROUND</p><h1>Less “what if.”<br /><em>More “let’s try.”</em></h1><p>Three things you can break. Move a slider until the model gets it wrong, assemble a prompt piece by piece, then make a call the tool can’t make for you.</p><nav className="studio-anchor-pills" aria-label="Experiments"><a href="#classifier">01 / Find patterns</a><a href="#prompt-builder">02 / Build a prompt</a><a href="#judgment">03 / Make the call</a></nav></div></section>
    <div className="landing-width studio-experiments">
      <section id="classifier" className="studio-experiment-section" tabIndex={-1}><Reveal className="studio-experiment-grid"><div><p className="studio-eyebrow">EXPERIMENT 01 / A TINY MODEL</p><h2>Banana or orange?<br /><em>Let the examples vote.</em></h2><p>Six labelled fruits, and a new one you control. The three nearest neighbours vote, and whatever they say becomes the answer — that is the entire algorithm.</p><ol className="studio-instructions"><li><span>01</span>Move a slider to change the new fruit’s measurements.</li><li><span>02</span>Watch the lines connect it to its three nearest neighbors.</li><li><span>03</span>Try a fruit that fits neither category. What does the model miss?</li></ol><div className="studio-insight"><Lightbulb size={20} /><p>A small dataset limits what a model can recognize. More confidence is not the same as more understanding.</p></div><Link className="studio-text-button" to="/learn?module=fundamentals">Explore the full lesson <ArrowUpRight size={16} /></Link></div><FruitClassifier /></Reveal></section>
      <section id="prompt-builder" className="studio-experiment-section" tabIndex={-1}><Reveal className="studio-experiment-grid"><div><p className="studio-eyebrow">EXPERIMENT 02 / INTENTION IN, IDEAS OUT</p><h2>A good prompt<br /><em>has a few ingredients.</em></h2><p>Pick your subject, then add context, a task, a format, and a plan for checking the response. See your study prompt take shape.</p><p>Copy it for an approved tool, or use it as a starting point for your own writing. Follow your teacher’s rules about AI assistance.</p><Link className="studio-text-button" to="/learn?module=tools">Learn to use AI thoughtfully <ArrowUpRight size={16} /></Link></div><PromptBuilder /></Reveal></section>
      <section id="judgment" className="studio-experiment-section" tabIndex={-1}><Reveal className="studio-experiment-grid"><div><p className="studio-eyebrow">EXPERIMENT 03 / YOU MAKE THE CALL</p><h2>The tool has an answer.<br /><em>You have a choice.</em></h2><p>Responsible AI use starts with the situation. Think about the assignment, whose work it is, and the difference between getting support and giving up your thinking.</p><Link className="studio-text-button" to="/learn?module=ethics">Explore ethical AI <ArrowUpRight size={16} /></Link></div><EthicsPreview /></Reveal></section>
    </div><section className="studio-inline-cta landing-width"><div><p className="studio-eyebrow">READY FOR YOUR NEXT CHAPTER?</p><h2>Turn experiments into understanding.</h2><p>Practice freely here. Earn XP and badges by completing quizzes in the learning studio.</p></div><Link className="landing-primary" to="/learn">Start a lesson <ArrowUpRight size={18} /></Link></section>
  </main><PublicSiteFooter /></div>;
}
