import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Award, BookOpen, BrainCircuit, Check, CheckCircle2, Clock3, Compass, Flame, Layers3, Lightbulb, Pencil, Search, ShieldCheck, Sparkles, Trophy, Wand2 } from 'lucide-react';
import { useProgress } from '../state/useProgress';
import { lessons, lessonMinutes, lessonXP, units } from '../data/portalCurriculum';
import { readWorkbook, stepDone, workbookKey } from '../lib/portalWorkbook';
import Certificate from '../components/Certificate';

const icons = [BrainCircuit, Compass, ShieldCheck, Wand2];
export default function PortalHomePage() {
  const { displayName, gradeLevel, completedModules, notesByModule, moduleScores, xp, streak, updateDisplayName } = useProgress();
  const { pathname } = useLocation();
  const [query, setQuery] = useState('');
  const [level, setLevel] = useState('All levels');
  const [name, setName] = useState(displayName);
  const [saved, setSaved] = useState(false);
  const [certificate, setCertificate] = useState(false);
  const progressView = pathname === '/progress';
  const complete = lessons.filter(lesson => completedModules.includes(lesson.id));
  const inProgress = lessons.filter(lesson => !completedModules.includes(lesson.id) && notesByModule[workbookKey(lesson.id)])
    .sort((a, b) => readWorkbook(notesByModule[workbookKey(b.id)]).updatedAt - readWorkbook(notesByModule[workbookKey(a.id)]).updatedAt)[0];
  const next = inProgress ?? lessons.find(lesson => !completedModules.includes(lesson.id));
  const percent = Math.round(complete.length / lessons.length * 100);
  const visible = lessons.filter(lesson => (level === 'All levels' || lesson.tags[0] === level) && [lesson.title, lesson.subtitle, ...lesson.tags, ...lesson.terms.flat()].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
  const badgeCount = units.filter(unit => lessons.filter(lesson => lesson.unit === unit.id).every(lesson => completedModules.includes(lesson.id))).length;
  const recentProjects = lessons.filter(lesson => readWorkbook(notesByModule[workbookKey(lesson.id)]).project.some(text => text.trim()));
  return <div className="academy-page academy-dashboard">
    {certificate && <Certificate onClose={() => setCertificate(false)} />}
    <header className="academy-greeting"><div><p className="academy-kicker">YOUR LEARNING SPACE / GRADES 9-12{gradeLevel ? ' / GRADE ' + gradeLevel : ''}</p><h1>{progressView ? 'Look at what you can do.' : 'Hey ' + displayName + ', let\u2019s figure AI out.'}</h1><p>{progressView ? 'Your skills, projects, and next steps, all in one place.' : 'Small discoveries. Real practice. A little more confidence every time.'}</p></div><span className="academy-streak"><Flame size={21} /><b>{streak}</b> day visit streak</span></header>
    <div className="academy-dashboard-top">
      <section className="academy-resume"><div className="academy-resume-copy"><span className="academy-kicker">{next ? inProgress ? 'PICK UP WHERE YOU LEFT OFF' : 'YOUR NEXT DISCOVERY' : 'YOUR PATH IS COMPLETE'}</span><h2>{next ? next.title : 'Eight lessons. A whole new way to think.'}</h2><p>{next ? next.subtitle : 'You have practiced, tested, questioned, and created. Keep your projects as evidence of what you can do.'}</p><div className="academy-tags"><span><Clock3 size={14} />{next ? 'About ' + lessonMinutes + ' minutes' : '8 lessons completed'}</span><span><Pencil size={14} />{next ? 'One project to make yours' : 'Your own learning portfolio'}</span></div><Link className="academy-button academy-button-light" to={next ? '/learn?lesson=' + next.id : '/learn?lesson=capstone'}>{next ? inProgress ? 'Continue my lesson' : 'Start this lesson' : 'Revisit my capstone'}<ArrowRight size={17} /></Link></div><div className="academy-progress-art"><svg viewBox="0 0 140 140" aria-hidden="true"><circle cx="70" cy="70" r="59" /><circle cx="70" cy="70" r="59" pathLength="100" strokeDasharray={percent + ' 100'} /></svg><div><strong>{complete.length}<small> / 8</small></strong><span>lessons complete</span></div><span className="academy-progress-caption">One step at a time.</span></div></section>
      <aside className="academy-how"><div className="academy-sticker"><Lightbulb size={27} /></div><p className="academy-kicker">THIS IS YOUR LAB</p><h2>Learn it. Try it.<br /> Make it yours.</h2><ol><li><span>01</span>Explore three bite-sized ideas.</li><li><span>02</span>Try a hands-on experiment.</li><li><span>03</span>Create, reflect, and check your skills.</li></ol><p>About {lessonMinutes} minutes per lesson. No countdown. Take the time you need.</p></aside>
    </div>
    <section className="academy-stats" aria-label="Learning statistics"><article><BookOpen size={21} /><div><strong>{complete.length}<small> / 8</small></strong><span>Lessons completed</span></div></article><article><Sparkles size={21} /><div><strong>{xp}</strong><span>Total XP / {lessonXP} per new lesson</span></div></article><article><Award size={21} /><div><strong>{badgeCount}<small> / 4</small></strong><span>Skill badges</span></div></article><article><Pencil size={21} /><div><strong>{recentProjects.length}</strong><span>Projects started</span></div></article></section>
    {complete.length === lessons.length && <section className="academy-celebration"><Trophy size={29} /><div><h2>You earned a moment to celebrate.</h2><p>All eight lessons are complete. Your certificate is ready.</p></div><button className="academy-button" type="button" onClick={() => setCertificate(true)}>View certificate <ArrowUpRight size={16} /></button></section>}
    <section aria-labelledby="course-heading" className="academy-roadmap"><div className="academy-section-heading"><div><p className="academy-kicker">{progressView ? 'YOUR SKILL ROADMAP' : 'THE FULL COURSE / ABOUT 3 HOURS 20 MINUTES'}</p><h2 id="course-heading">{progressView ? 'See the work behind your progress.' : 'Eight lessons. Four useful superpowers.'}</h2><p>Start with the basics or jump to a topic. Every lesson includes practice, a project, and feedback.</p></div></div><div className="academy-filters"><label className="academy-search"><Search size={19} /><span className="sr-only">Search the curriculum</span><input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search topics, skills, or vocabulary..." /></label><label><span className="sr-only">Filter by level</span><select value={level} onChange={e => setLevel(e.target.value)}>{['All levels', 'Beginner', 'Core', 'Challenge'].map(item => <option key={item}>{item}</option>)}</select></label><span role="status">{visible.length} lessons</span></div>
      <div className="academy-units">{units.map((unit, i) => {
        const unitLessons = visible.filter(lesson => lesson.unit === unit.id);
        if (!unitLessons.length) return null;
        const Icon = icons[i];
        const earned = lessons.filter(lesson => lesson.unit === unit.id).every(lesson => completedModules.includes(lesson.id));
        return <section className="academy-unit" key={unit.id}><header><div className="academy-unit-icon"><Icon size={25} /></div><div><p className="academy-kicker">UNIT {unit.number}</p><h3>{unit.title}</h3><p>{unit.description}</p></div><span className={'academy-badge-label ' + (earned ? 'is-earned' : '')}><Award size={16} />{earned ? unit.badge + ' earned' : 'Earn: ' + unit.badge}</span></header><div className="academy-lesson-grid">{unitLessons.map(lesson => {
          const work = readWorkbook(notesByModule[workbookKey(lesson.id)]);
          const done = completedModules.includes(lesson.id);
          const steps = Array.from({ length: 6 }, (_, index) => index).filter(index => stepDone(lesson, work, index)).length;
          return <Link key={lesson.id} className="academy-lesson-card" to={'/learn?lesson=' + lesson.id}><div className="academy-card-top"><span className="academy-lesson-number">{String(lessons.indexOf(lesson) + 1).padStart(2, '0')}</span><span className="academy-level">{lesson.tags[0]}</span>{done && <CheckCircle2 size={20} />}</div><h4>{lesson.title}</h4><p>{lesson.subtitle}</p><div className="academy-tags"><span><Clock3 size={13} />25 min</span><span>{lesson.tags[1]}</span><span>{lessonXP} XP</span></div><div className="academy-card-progress"><progress max={6} value={done ? 6 : steps} aria-label={lesson.title + ' progress'} /><span>{done ? 'Completed' : steps ? steps + '/6 checkpoints' : 'Ready when you are'}</span></div>{moduleScores[lesson.id] !== undefined && <small>Best mastery score: {moduleScores[lesson.id]}%</small>}<span className="academy-card-action">{done ? 'Revisit lesson' : notesByModule[workbookKey(lesson.id)] ? 'Continue learning' : 'Let\u2019s explore'}<ArrowRight size={17} /></span></Link>;
        })}</div></section>;
      })}</div>
      {visible.length === 0 && <div className="academy-empty"><Search size={25} /><h3>No matching lessons yet.</h3><p>Try data, privacy, or design or show all levels.</p><button className="academy-secondary" type="button" onClick={() => { setQuery(''); setLevel('All levels'); }}>Clear filters</button></div>}
    </section>
    <div className="academy-dashboard-bottom"><section className="academy-portfolio"><span className="academy-kicker">YOUR THINKING IS THE POINT</span><h2>Your project shelf</h2><p>A collection of ideas you can explain, not just answers you clicked.</p>{recentProjects.length ? <ul>{recentProjects.map(lesson => <li key={lesson.id}><Pencil size={17} /><div><Link to={'/learn?lesson=' + lesson.id}>{lesson.project.title}<ArrowRight size={14} /></Link><span>{completedModules.includes(lesson.id) ? 'Lesson complete' : 'Draft saved'} / {lesson.title}</span></div></li>)}</ul> : <div className="academy-shelf-empty"><Layers3 size={31} /><p>Your first project goes here. Start a lesson and your draft will appear automatically.</p></div>}</section><section className="academy-study-plan"><span className="academy-kicker">A LITTLE STRUCTURE HELPS</span><h2>Make room for learning.</h2><p>Try two lessons a week. That is one unit, two small projects, and a new skill to use in class.</p><ul><li><Check size={15} />Week 1: understand the machine</li><li><Check size={15} />Week 2: build your study toolkit</li><li><Check size={15} />Week 3: think about people</li><li><Check size={15} />Week 4: create and share a proposal</li></ul><details className="academy-details"><summary>Personalize your display name</summary><form onSubmit={e => { e.preventDefault(); if (name.trim()) { updateDisplayName(name); setSaved(true); } }}><label className="academy-field">Name or nickname<input value={name} required maxLength={40} onChange={e => { setName(e.target.value); setSaved(false); }} /></label><button className="academy-button" type="submit">Save name</button><p role="status">{saved ? 'Name saved.' : ''}</p></form></details></section></div>
    <footer className="academy-storage"><ShieldCheck size={18} /><p>Progress, projects, and notes save in this browser on this device. Earlier XP and notes are kept; the expanded lessons have their own completion steps. Download workbooks from a lesson to keep a copy.</p></footer>
  </div>;
}
