import { useState } from 'react';
import { ArrowUpRight, BookOpen, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PublicSiteFooter, PublicSiteHeader } from '../components/PublicSiteChrome';
import { learningResources } from '../data/resources';
export default function ResourcesPage() {
  const [query, setQuery] = useState('');
  const results = learningResources.filter(resource => `${resource.name} ${resource.title} ${resource.category} ${resource.description}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <div className="signal-landing studio-interior"><PublicSiteHeader /><main id="main-content" tabIndex={-1}><section className="studio-page-hero"><div className="landing-width"><p className="studio-eyebrow"><BookOpen size={17} /> THE READING ROOM</p><h1>Follow your curiosity.<br /><em>Check your sources.</em></h1><p>A small, purposeful collection of educational resources to help you explore beyond the lesson.</p></div></section><section className="landing-width studio-resource-library"><label className="studio-resource-search"><Search size={19} /><span className="sr-only">Search learning resources</span><input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search a topic or organization" /></label><p className="studio-result-count" role="status">{results.length} resource{results.length === 1 ? '' : 's'} found · External links open in a new tab</p><div className="studio-resource-grid">{results.map((resource, index) => <a key={resource.name} className="studio-resource-card" href={resource.url} target="_blank" rel="noopener noreferrer"><div><span className="resource-monogram">{resource.mark}</span><span>0{index + 1}</span></div><span className="studio-eyebrow">{resource.category}</span><h2>{resource.title}</h2><p>{resource.description}</p><span className="resource-card-link">{resource.name}<ArrowUpRight size={20} /><span className="sr-only"> (opens in a new tab)</span></span></a>)}</div>{results.length === 0 && <div className="studio-empty"><h2>No matches yet.</h2><p>Try “ethics,” “learning,” or an organization’s name.</p><button className="studio-text-button" type="button" onClick={() => setQuery('')}>Show all resources <ArrowUpRight size={16} /></button></div>}<p className="studio-resource-disclosure">These organizations provide the linked resources. Their inclusion does not imply sponsorship, partnership, or endorsement of Signal Lab.</p></section><section className="studio-inline-cta landing-width"><div><p className="studio-eyebrow">BEFORE YOU USE THE ANSWER</p><h2>Make good judgment a habit.</h2><p>A five-point guide to checking AI output and keeping your work your own.</p></div><Link className="landing-primary" to="/field-guide">Open the Field Guide <ArrowUpRight size={18} /></Link></section></main><PublicSiteFooter /></div>;
}
